#!/system/bin/sh
# =============================================================
# PROBE / DIAGNOSTIC untuk tweak module HP
# Target : Realme GT Neo 2 (SD870), Shizuku shell (UID 2000)
# Sifat  : READ-ONLY. Hanya 1 tes-tulis yang langsung di-restore.
# Tujuan : cari tau APA yang device-mu benar-benar baca, sebelum
#          kita optimasi. Jangan nembak buta ratusan properti.
#
# Cara pakai (via Shizuku terminal / LADB / adb shell):
#   sh /sdcard/probe.sh 2>&1 | tee /sdcard/probe-report.txt
# Lalu paste isi probe-report.txt balik ke Claude.
# =============================================================

line() { echo "----------------------------------------------------------"; }
sect() { echo; line; echo "## $1"; line; }

echo "PROBE REPORT  (paste seluruhnya balik ke Claude)"
echo "generated by probe.sh"

# -------------------------------------------------------------
sect "0. IDENTITAS EKSEKUSI (siapa yang menjalankan?)"
echo "uid           : $(id -u 2>/dev/null) ($(id -un 2>/dev/null))"
echo "id lengkap    : $(id 2>/dev/null)"
# UID 0 = root, 2000 = shell (Shizuku/adb). Menentukan batas kemampuan.
if [ "$(id -u)" = "0" ]; then echo "MODE          : ROOT"; else echo "MODE          : SHELL (non-root / Shizuku)"; fi

# -------------------------------------------------------------
sect "1. IDENTITAS DEVICE & BUILD"
echo "model         : $(getprop ro.product.model)"
echo "device        : $(getprop ro.product.device)"
echo "android       : $(getprop ro.build.version.release) (SDK $(getprop ro.build.version.sdk))"
echo "build type    : $(getprop ro.build.type)"       # user / userdebug / eng
echo "debuggable    : $(getprop ro.debuggable)"        # 1 = banyak debug.* dibaca
echo "SoC           : $(getprop ro.board.platform) / $(getprop ro.soc.model)"
echo "kernel        : $(uname -r)"
echo "cores (nproc) : $(nproc --all 2>/dev/null)"

# -------------------------------------------------------------
sect "2. TES-TULIS PROPERTI (apakah setprop debug.* nyangkut?)"
# Ini SATU-SATUNYA tulis. Kita set nilai unik, baca balik, lalu hapus.
TESTKEY="debug.claude.probe"
setprop "$TESTKEY" 12345 2>/dev/null
RB="$(getprop "$TESTKEY")"
if [ "$RB" = "12345" ]; then
  echo "setprop debug.*  : BISA (readback=$RB) -> Shizuku boleh set debug props"
else
  echo "setprop debug.*  : GAGAL (readback='$RB') -> banyak script bakal no-op buatmu"
fi
setprop "$TESTKEY" "" 2>/dev/null   # restore/kosongkan

# -------------------------------------------------------------
sect "3. THERMAL (ini variabel paling berpengaruh di skenario 'ramai')"
echo ">> Status thermal service saat ini:"
dumpsys thermalservice 2>/dev/null | grep -iE "status|override|is throttling|Temperature" | head -n 30
echo
echo ">> Thermal zones aktif (nama + suhu mentah):"
for z in /sys/class/thermal/thermal_zone*; do
  [ -r "$z/type" ] || continue
  printf "  %-22s = %s\n" "$(cat "$z/type" 2>/dev/null)" "$(cat "$z/temp" 2>/dev/null)"
done 2>/dev/null | head -n 40
echo
echo "(catatan: 'cmd thermalservice override-status 0' butuh dites terpisah;"
echo " di sebagian ROM butuh izin lebih dari shell. Probe TIDAK mengubahnya.)"

# -------------------------------------------------------------
sect "4. SURFACEFLINGER — model vsync mana yang dipakai?"
# Menentukan apakah phase_offset (lama) atau workDuration (baru) yang relevan.
echo ">> Refresh rate & mode:"
dumpsys SurfaceFlinger 2>/dev/null | grep -iE "refresh|fps|mode |DisplayMode" | head -n 20
echo
echo ">> Nilai phase-offset / duration yang KINI dibaca SF:"
for p in \
  debug.sf.use_phase_offsets_as_durations \
  debug.sf.early_phase_offset_ns \
  debug.sf.early.app.duration \
  debug.sf.late.sf.duration \
  debug.sf.latch_unsignaled \
  debug.sf.disable_backpressure ; do
  printf "  %-42s = '%s'\n" "$p" "$(getprop $p)"
done

# -------------------------------------------------------------
sect "5. CPU / GPU GOVERNOR & FREKUENSI (bisa dibaca shell?)"
echo ">> Governor per policy:"
for pol in /sys/devices/system/cpu/cpufreq/policy*; do
  [ -r "$pol/scaling_governor" ] || continue
  printf "  %s : gov=%s  cur=%s  max=%s\n" \
    "$(basename $pol)" \
    "$(cat $pol/scaling_governor 2>/dev/null)" \
    "$(cat $pol/scaling_cur_freq 2>/dev/null)" \
    "$(cat $pol/scaling_max_freq 2>/dev/null)"
done 2>/dev/null
echo
echo ">> GPU (Adreno) — path umum Qualcomm:"
GPU=/sys/class/kgsl/kgsl-3d0
if [ -r "$GPU/gpuclk" ]; then
  echo "  gpuclk    : $(cat $GPU/gpuclk 2>/dev/null)"
  echo "  governor  : $(cat $GPU/devfreq/governor 2>/dev/null)"
  echo "  max_freq  : $(cat $GPU/devfreq/max_freq 2>/dev/null)"
else
  echo "  (tidak bisa baca $GPU — mungkin butuh root)"
fi

# -------------------------------------------------------------
sect "6. DEVICE_CONFIG (flag eksperimen server — kandidat cleanup nyata)"
CNT=$(cmd device_config list 2>/dev/null | wc -l)
echo "total entri device_config : $CNT"
echo ">> namespace yang sering berdampak ke perf/game:"
cmd device_config list 2>/dev/null | grep -iE "game|graphics|surface|activity_manager|display|power|thermal" | head -n 25

# -------------------------------------------------------------
sect "7. BASELINE FPS (framestats) — ISI PACKAGE GAME dulu!"
# Ganti PKG ke game yang mau diukur. Default: PUBGM global.
PKG="com.tencent.ig"
echo "package diukur: $PKG (ubah variabel PKG di script kalau beda)"
echo ">> reset & baca gfxinfo (mainkan game ~30 detik SEBELUM jalankan bagian ini idealnya):"
dumpsys gfxinfo "$PKG" 2>/dev/null | grep -iE "Total frames|Janky|percentile|Number Missed" | head -n 12
echo "(kalau kosong: game belum jalan / package beda / belum pernah render)"

# -------------------------------------------------------------
sect "8. POWER / SAVER STATE (yang benar-benar berefek dari script kedua)"
echo "low_power              : $(settings get global low_power)"
echo "low_power_sticky       : $(settings get global low_power_sticky)"
echo "cached_apps_freezer    : $(settings get global cached_apps_freezer)"
echo "restricted_perf        : $(settings get global restricted_device_performance)"
echo "window_animation_scale : $(settings get global window_animation_scale)"

sect "SELESAI"
echo "Paste seluruh output ini balik ke Claude untuk analisis lanjutan."
